### ISSUE TITLE
Is this an Android-only fork of Ejecta?

### ISSUE THREAD

**Issue by idibidiart** [Wizcorp/Ejecta-X#97]
I realize this is a fork of Ejecta for iOS

1. Does this fork support both Android and iOS or only Android?

2. Is it API compatible with the latest Ejecta for iOS, so that one JS codebase can run on both Android and iOS?

Thanks for making this :)

**Comment by jrouault** [comment]
Thank you for your interest in this project. This is not an actual fork of Ejecta for iOS but we did try to keep them as close as possible.
1. It currently supports only Android.
2. Every feature of Ejecta for iOS has yet to be implemented, so the API is not fully compatible per se.
Before having a go at this project, I invite to read my comment here: https://github.com/Wizcorp/Ejecta-X/issues/20#issuecomment-109110807.
